/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLASES.funcionario;
import PERSISTENCIA.CPrincipal;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franc
 */
public class administrarfuncionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form administrarfuncionarios
     */
     public static funcionario funcio=null;
         public static boolean activo = false;
         int cantidaddecarnets=0;
    public administrarfuncionarios() {
        initComponents();
        cargartabla();
        activo=true;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mdl1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jDateChooserCarnet = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jDateChooserBrebet = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setClosable(true);
        setTitle("ADMINISTAR FUNCIONARIOS");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        mdl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "FechaNacimiento", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mdl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mdl1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mdl1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CARNETS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jDateChooserCarnet.setDateFormatString("dd-MM-yyyy");

        jButton1.setText("Renovar Carné Salud");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooserBrebet.setDateFormatString("dd-MM-yyyy");

        jButton2.setText("Renovar Brebet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserBrebet, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jDateChooserCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooserBrebet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jDateChooserCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jButton3.setText("Limpiar campos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Modificar Otros Datos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cambiar Cargo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Horarios");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(16, 16, 16)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mdl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mdl1MouseClicked
    vaciarcampos();
        funcio = (funcionario) mdl1.getValueAt(mdl1.getSelectedRow(), 0);
        
 if (evt.getClickCount() == 2) {
           int i;
            JOptionPane.showMessageDialog(null,
                    "Nombre: " + funcio.getNombre() + "\n"
                    + "Apellido: " + funcio.getApellido()+ "\n"
                    + "Celular: " + funcio.getCelular()+ "\n"
                    + "Cedula: " + funcio.getCedula()+ "\n"
                        
                     + carnetsfuncio(funcio)

                   );
        }     
        
        // TODO add your handling code here:
         
         cantidaddecarnets=0;
         if(funcio !=null){
         cantidaddecarnets=funcio.getCarnetsdelfuncionario().size();
         
         for (int i = 0; i < cantidaddecarnets; i++) {
             if(funcio.getCarnetsdelfuncionario().get(i).getTipocarnet().equals("Carne Brebet")){
          jDateChooserBrebet.setDate(funcio.getCarnetsdelfuncionario().get(i).getFechavencimiento());
             }else{
          jDateChooserCarnet.setDate(funcio.getCarnetsdelfuncionario().get(i).getFechavencimiento());
             }
        }
         }
         
         
         
                
    }//GEN-LAST:event_mdl1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Date hoy = new Date();
        for (int i = 0; i < funcio.getCarnetsdelfuncionario().size(); i++) {
             if(funcio.getCarnetsdelfuncionario().get(i).getTipocarnet().equals("Carne Brebet")){
          funcio.getCarnetsdelfuncionario().get(i).setFechaRenovacion(hoy);
          funcio.getCarnetsdelfuncionario().get(i).setFechavencimiento(jDateChooserBrebet.getDate());
          JOptionPane.showMessageDialog(null, "Fecha de Vencimiento modificada correctamente", null, JOptionPane.OK_OPTION);
             }else{
         
             }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date hoy = new Date();
        for (int i = 0; i < funcio.getCarnetsdelfuncionario().size(); i++) {
             if(funcio.getCarnetsdelfuncionario().get(i).getTipocarnet().equals("Carne de salud")){
          funcio.getCarnetsdelfuncionario().get(i).setFechaRenovacion(hoy);
          funcio.getCarnetsdelfuncionario().get(i).setFechavencimiento(jDateChooserCarnet.getDate());
          JOptionPane.showMessageDialog(null, "Fecha de Vencimiento modificada correctamente", null, JOptionPane.OK_OPTION);
             }else{
         
             }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        activo=false;
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        vaciarcampos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         addfuncionario.funcio2= funcio;
        if (addfuncionario.activo == false) {
            addfuncionario AU = new addfuncionario();           
            main.jDesktopPane1.add(AU);
            AU.setVisible(true);
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     cargarrenovacion.funcio3= funcio;
        if (cargarrenovacion.activo == false) {
            cargarrenovacion AU = new cargarrenovacion();           
            main.jDesktopPane1.add(AU);
            AU.setVisible(true);
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       asignarhorarios.funcionariohorario= funcio;
        if (asignarhorarios.activo == false) {
            asignarhorarios AU = new asignarhorarios();           
            main.jDesktopPane1.add(AU);
            AU.setVisible(true);
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
public void cargartabla() {
        DefaultTableModel md1 = (DefaultTableModel) mdl1.getModel();
        md1.setRowCount(0);
        Iterator<funcionario> it = main.funcionarios.iterator();
        while (it.hasNext()) {
            funcionario next = it.next();
      //      if (next.isEliminado() != true) {
                //Object[] fila = new Object[5];
                Object[] fila = new Object[5];
                fila[0] = next;
                fila[1] = next.getApellido();
                fila[2] = next.getCedula();
                fila[4] = next.getCelular();
                fila[3] = next.getFechaNacimiento();
                md1.addRow(fila);
                //fila[3] = next.getTelefonos();
                //fila[4] = next.getRepartidores();
                
          //  }
        }
    }
public void vaciarcampos(){
    jDateChooserBrebet.setCalendar(null);
    jDateChooserCarnet.setCalendar(null);
    funcio=null;
}
public String carnetsfuncio (funcionario funcio){
    String carnets = "";
    int cantidadcarne=funcio.getCarnetsdelfuncionario().size();
    if(cantidadcarne==0){
        return "";
    }else{
        carnets +="Carnets Datos: \n";
   
    for (int i = 0; i < cantidadcarne; i++) {
        carnets +="-"+funcio.getCarnetsdelfuncionario().get(i).getTipocarnet()+" Fecha vencimiento: \n";
             carnets+=funcio.getCarnetsdelfuncionario().get(i).getFechavencimiento()+"\n";
                if(funcio.getCarnetsdelfuncionario().get(i).getFechaRenovacion()==null){
                
                }else{
                    carnets+="Fecha de ultima renovacion:"+funcio.getCarnetsdelfuncionario().get(i).getFechaRenovacion()+"\n";
                } 
              
    }
    return carnets; 
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooserBrebet;
    private com.toedter.calendar.JDateChooser jDateChooserCarnet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable mdl1;
    // End of variables declaration//GEN-END:variables
}
