/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLASES.carnets;
import CLASES.funcionario;
import static GUI.administrarfuncionarios.mdl1;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franc
 */
public class funcionariosvencidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form funcionariosvencidos
     */
    public static boolean activo = false;
    public funcionariosvencidos() {
        initComponents();
        activo=true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mdl1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        mdl2 = new javax.swing.JTable();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("10 dias o menos para vencimiento");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("VENCIDOS!");

        mdl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "obj", "Nombre", "Apellido", "Carnet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mdl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mdl1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mdl1);
        if (mdl1.getColumnModel().getColumnCount() > 0) {
            mdl1.getColumnModel().getColumn(0).setMinWidth(0);
            mdl1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        mdl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "obj", "Nombre", "Apellido", "Carnet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mdl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mdl2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mdl2);
        if (mdl2.getColumnModel().getColumnCount() > 0) {
            mdl2.getColumnModel().getColumn(0).setMinWidth(0);
            mdl2.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mdl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mdl1MouseClicked
//        vaciarcampos();
//        funcio = (funcionario) mdl1.getValueAt(mdl1.getSelectedRow(), 0);
//
//        if (evt.getClickCount() == 2) {
//            int i;
//            JOptionPane.showMessageDialog(null,
//                "Nombre: " + funcio.getNombre() + "\n"
//                + "Apellido: " + funcio.getApellido()+ "\n"
//                + "Celular: " + funcio.getCelular()+ "\n"
//                + "Cedula: " + funcio.getCedula()+ "\n"
//
//                + carnetsfuncio(funcio)
//
//            );
//        }
//
//        // TODO add your handling code here:
//
//        cantidaddecarnets=0;
//        if(funcio !=null){
//            cantidaddecarnets=funcio.getCarnetsdelfuncionario().size();
//
//            for (int i = 0; i < cantidaddecarnets; i++) {
//                if(funcio.getCarnetsdelfuncionario().get(i).getTipocarnet().equals("Carne Brebet")){
//                    jDateChooserBrebet.setDate(funcio.getCarnetsdelfuncionario().get(i).getFechavencimiento());
//                }else{
//                    jDateChooserCarnet.setDate(funcio.getCarnetsdelfuncionario().get(i).getFechavencimiento());
//                }
//            }
//        }

    }//GEN-LAST:event_mdl1MouseClicked

    private void mdl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mdl2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mdl2MouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        activo=false;
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

public static void cargartablavencidos() {
        DefaultTableModel md1 = (DefaultTableModel) mdl1.getModel();
        md1.setRowCount(0);
        Iterator<carnets> it = main.funcionariosconcarnetvencido.iterator();
        while (it.hasNext()) {
            carnets next = it.next();
      //      if (next.isEliminado() != true) {
                //Object[] fila = new Object[5];
                Object[] fila = new Object[4];
                fila[0] = next;
                fila[1] = next.getFuncionariodueniodelcarne();
                fila[2] = next.getFuncionariodueniodelcarne().getApellido();
                fila[3] = next.getTipocarnet();
                md1.addRow(fila);
                //fila[3] = next.getTelefonos();
                //fila[4] = next.getRepartidores();
                
          //  }
        }
    }
public static void cargartablaporvencer() {
        DefaultTableModel md2 = (DefaultTableModel) mdl2.getModel();
        md2.setRowCount(0);
        Iterator<carnets> it = main.funcionariosconcarnetporvencer.iterator();
        while (it.hasNext()) {
            carnets next = it.next();
      //      if (next.isEliminado() != true) {
                //Object[] fila = new Object[5];
                Object[] fila = new Object[4];
                fila[0] = next;
                fila[1] = next.getFuncionariodueniodelcarne();
                fila[2] = next.getFuncionariodueniodelcarne().getApellido();
                fila[3] = next.getTipocarnet();
                md2.addRow(fila);
                //fila[3] = next.getTelefonos();
                //fila[4] = next.getRepartidores();
                
          //  }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable mdl1;
    public static javax.swing.JTable mdl2;
    // End of variables declaration//GEN-END:variables
}
