/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLASES.funcionario;
import CLASES.observacion;
import static GUI.administrarfuncionarios.funcio;
import PERSISTENCIA.CPrincipal;
import java.awt.Font;

import java.util.Iterator;
import javax.persistence.FetchType;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.cfg.AnnotationBinder;

/**
 *
 * @author franc
 */
public class listobs extends javax.swing.JInternalFrame {

    /**
     * Creates new form listobs
     */
    JLabel label = new JLabel();
    public static funcionario funcio = null;
    public static boolean activo = false;

    public listobs() {
        initComponents();
        activo = true;
        cargartabla();
        desactivarbotones();
    }

    public void cargartabla() {
        DefaultTableModel md1 = (DefaultTableModel) mdl1.getModel();
        md1.setRowCount(0);
        Iterator<observacion> it = funcio.getObservaciones().iterator();
        while (it.hasNext()) {
            observacion next = it.next();
            //      if (next.isEliminado() != true) {
            //Object[] fila = new Object[5];
            Object[] fila = new Object[3];
            fila[0] = next;
            fila[1] = next.getGravedad();
            fila[2] = next.getFechaobservacion();
            md1.addRow(fila);
            //fila[3] = next.getTelefonos();
            //fila[4] = next.getRepartidores();

            //  }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mdl1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(28, 28, 28));
        setClosable(true);
        setTitle("Lista de Observaciones");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/editar.png"))); // NOI18N
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        mdl1.setBackground(new java.awt.Color(28, 28, 28));
        mdl1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mdl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Motivo", "Tipo", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mdl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mdl1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mdl1);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/delete.png"))); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(432, 432, 432)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        activo = false;
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing
    public void desactivarbotones(){
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
    }
       public void activarbotones(){
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
    }
    private void mdl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mdl1MouseClicked
       activarbotones();
        observacion prod = (observacion) mdl1.getValueAt(mdl1.getSelectedRow(), 0);
        if (evt.getClickCount() == 2) {
            label.setText("<html>Nombre Funcionario Observado: " + prod.getFuncionariobservado().getNombre() + "<br>"
                    + "Motivo: " + prod.getDescripcion() + "<br>"
                    + "Tipo: " + prod.getGravedad() + "<br>"
                    + "Fecha: " + prod.getFechaobservacion() + "<br>");
            label.setFont(new Font("Arial", Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "Producto", JOptionPane.INFORMATION_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_mdl1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        observacion observacion = (observacion) mdl1.getValueAt(mdl1.getSelectedRow(), 0);
        CPrincipal.getInstance().delete(observacion);
        CPrincipal.getInstance().refresh(funcio);
        cargartabla();
        JOptionPane.showMessageDialog(null, "Observacion eliminada correctamente", "Obseravacion", JOptionPane.INFORMATION_MESSAGE);
        desactivarbotones();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         
        if (observarfuncionario.activo == false) { 
           observarfuncionario.funcio=funcio; 
           observarfuncionario.estadomodificiar=true; 
           observarfuncionario.obstoedit= (observacion) mdl1.getValueAt(mdl1.getSelectedRow(), 0);
            observarfuncionario AU = new observarfuncionario(); 
           
           
            
            main.jDesktopPane1.add(AU);
            AU.setVisible(true);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mdl1;
    // End of variables declaration//GEN-END:variables
}
